---
# Ansible Galaxy Requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.5.4"
  - name: community.general
    version: ">=8.0.0"
  - name: devsec.hardening
    version: ">=8.0.0"

roles:

  # Jeff Geerling (geerlingguy) Roles
  - name: geerlingguy.nginx

  - name: geerlingguy.repo-remi

  - name: geerlingguy.php

  - name: geerlingguy.redis

  - name: geerlingguy.security
